---
- name: Install Nginx
  hosts: target  #same name to be specified in the inventory file hosts.ini
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
